production:
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>
      options:
        skip_version_check: true
        safe: true
development:
  sessions:
    default:
      database: blackacrereports_development
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: blackacrereports_test
      hosts:
        - localhost:27017
